### ISSUE TITLE
Seems to be not working on Rails 4.2.0.beta2

### ISSUE THREAD

**Issue by jhephs** [softace/activerecord-tableless#22]
```
class Customer < ActiveRecord::Base

  has_no_table

  column :id, :integer

end

```

```
> Customer.new
(Object doesn't support #inspect)
=>
```

I'm using version 1.3.4 of this gem by the way. Thanks!!

**Comment by randoum** [comment]
A possible begining of a solutions would be to replace

```
def column(name, sql_type = nil, default = nil, null = true)
  tableless_options[:columns] << ActiveRecord::ConnectionAdapters::Column.new(name.to_s, default, sql_type.to_s, null)
end
```

by

```
def column(name, sql_type = nil, default = nil, null = true)
  type = "ActiveRecord::Type::#{sql_type.to_s.humanize}".camelize.new
  tableless_options[:columns] << ActiveRecord::ConnectionAdapters::Column.new(name.to_s, default, type, null)
end
```

PS: I am not using activerecord-tableless, just found that PR through google and posted a solution that works for me, hope it can help

**Comment by fguillen** [comment]
Same here with Rails `4.2.0` I can't make the @randoum's workaround to work :/

**Comment by chip-miller** [comment]
There is a pull request that fixes this issue (https://github.com/softace/activerecord-tableless/pull/23).  It would be good to see it merged in :)

**Comment by dale-ackerman** [comment]
This issue still exists when using Postgresql (pg) adapter.  I get errors when using :string.  Have been able to work around this by using :varchar

**Comment by kreintjes** [comment]
I can confirm @dale-ackerman 's problem

**Comment by blarralde** [comment]
Just got into the issue. What @randoum posted looks hacky but works better than this commit: https://github.com/david135/activerecord-tableless/commit/800393c52bd254f812e89d75f028a5d0730e79d9

**Comment by Seliestel** [comment]
I could make it work with @randoum workaround, just by changing a little bit his code to:

  def self.column(name, sql_type = nil, default = nil, null = true)
    type = "ActiveRecord::Type::#{sql_type.to_s.camelize}".constantize.new
    columns << ActiveRecord::ConnectionAdapters::Column.new(name.to_s, default, type, null)
  end

Thanks

**Comment by shekharkhanna** [comment]
@seliestel Worked like a charm

Thanks

**Comment by jarl-dk** [comment]
Sorry for being away for some time, I'll take a look at this and catch up... Thanks for the error report.

**Comment by samu** [comment]
same problem :sob:

**Comment by aeberlin** [comment]
Same problem here, let me know if we can do anything to help.

**Comment by rhomeister** [comment]
I found another problem when I define an association: 

`undefined method `val' for #<Arel::Nodes::BindParam>`

Stack trace: 

```
 () home/rhomeister/.rvm/gems/ruby-2.2.2/bundler/gems/squeel-96815373ebdc/lib/squeel/adapters/active_record/4.2/relation_extensions.rb:107:in `block (2 levels) in where_values_hash_with_squeel'
   () home/rhomeister/.rvm/gems/ruby-2.2.2/bundler/gems/squeel-96815373ebdc/lib/squeel/adapters/active_record/4.2/relation_extensions.rb:103:in `block in where_values_hash_with_squeel'
   () home/rhomeister/.rvm/gems/ruby-2.2.2/bundler/gems/squeel-96815373ebdc/lib/squeel/adapters/active_record/4.2/relation_extensions.rb:101:in `where_values_hash_with_squeel'
  activerecord (4.2.1) lib/active_record/relation.rb:579:in `scope_for_create'
  activerecord (4.2.1) lib/active_record/associations/collection_association.rb:513:in `create_scope'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/associations.rb:6:in `block in build_record'
  activerecord (4.2.1) lib/active_record/core.rb:283:in `initialize'
  activerecord (4.2.1) lib/active_record/inheritance.rb:61:in `new'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/reflection.rb:6:in `build_association'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/associations.rb:5:in `build_record'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/associations.rb:19:in `build'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/nested_attributes.rb:117:in `block in assign_nested_attributes_for_collection_association'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/nested_attributes.rb:112:in `assign_nested_attributes_for_collection_association'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/nested_attributes.rb:37:in `invitations_attributes='
  activerecord (4.2.1) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
  activerecord (4.2.1) lib/active_record/attribute_assignment.rb:65:in `block in assign_nested_parameter_attributes'
  activerecord (4.2.1) lib/active_record/attribute_assignment.rb:65:in `assign_nested_parameter_attributes'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/attribute_assignment.rb:71:in `assign_attributes'
  protected_attributes (1.0.9) lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
  activerecord (4.2.1) lib/active_record/core.rb:281:in `initialize'
  activerecord (4.2.1) lib/active_record/inheritance.rb:61:in `new'
  app/controllers/bulk_invitations_controller.rb:11:in `create'
```

```
class BulkInvitation < ActiveRecord::Base                                                                                                                                                                                                
   has_no_table                                                                                                                                                                                                                                          
   column :id, :integer
   has_many :invitations
   attr_accessible :invitations_attributes                                                                                                                                                                                                
end   
```

The `invitation` class is a normal ActiveRecord class.

I get the stack trace above when executing
`@bulk_invitation = BulkInvitation.new(params[:bulk_invitation])`

Used to work in 4.1.9, but broke when I upgraded to 4.2.1.

**Comment by kreintjes** [comment]
@rhomeister I believe you should also define `accepts_nested_attributes_for :invitations` in the BulkInvitation class. Not sure if this is causing your problem though.

Also, attr_accessible is from Rails 3.x, maybe it is time to upgrade to Strong Parameters. Maybe you could try to remove this call (and possibly even the protected_attributes gem) and see if this might be causing the problem.

**Comment by rhomeister** [comment]
Hi @kreintjes, I copied a severely abbreviated version of this class, and accidentally omitted the `accepts_nested_attributes_for` call. This is not causing the problem.

You're absolutely right about attr_accessible. This is indeed a remnant from Rails 3.x, but haven't gotten around to removing it yet. I'll have a look to see if this is the cause of the problem, although I have my doubts.

I feel this gem is not ready for Rails 4.2 yet, and since I have only 1 tableless model, I think I'll just create some dummy tables instead.

**Comment by dsusco** [comment]
I'm bumping into this same issue after upgrading an app to 4.2.5. Any change of pamplemousse's pull getting merged? Any good work-arounds if it isn't?

**Comment by mxsmith** [comment]
I have the same issue as @dsusco

**Comment by mxsmith** [comment]
I used @Pamplemousse branch using:
`gem "activerecord-tableless", git:'https://github.com/Pamplemousse/activerecord-tableless.git'`

However now I get the error:
`undefined method `prepared_statements' for #<Object:0x007fed3ba02be0>`

**Comment by tylercloke** [comment]
I am also seeing this in all versions of rails 4.2, including 4.2.6. Any workarounds?

**Comment by tylercloke** [comment]
Was hitting this:

`NoMethodError Exception: undefined method `type_cast_from_user' for "string":String` on all versions of Rails 4.2.

Changed my Gemfile to have:

`gem 'activerecord-tableless', :git => 'https://github.com/Pamplemousse/activerecord-tableless.git', :ref => 'fdc83fc11ff1982cd773c754e35cb720c5152a40'` to pull in his commit and things started working again (on rails 4.2.6)! Please get this merged into master :)

**Comment by ryanbarkley** [comment]
I also experienced this issue with rails 4.2.6 and tylercloke's Gemfile reference worked for me. I'm using the pg gem instead of sqlite3 for database, but not sure if that's relevant since this is a tableless model.

**Comment by rogerneel** [comment]
I also ran into this with Rails 4.2 and can confirm the @Pamplemousse fix. It also has backwards compatibility with Rails 4.1 and prior. Is this project still being maintained?

**Comment by shreyas123** [comment]
any luck with prepared_statement issue ? 

I am using ActiveRecord 4.2.6 and encountering this issue of prepared_statement

**Comment by vicocas** [comment]
@mxsmith | @shreyas123 Did you find an explanation/solution to the prepared_statement problem? I'm going through this right now upgrading to Rails 4.2.8
