### PR TITLE
fix for rails-4.2.0.betaX

### PR DESCRIPTION
**Pull request by david135**
This stopped working in the Rails 4.2 beta. This seems to get it working, but it isn't comprehensively checked.

### CODE REVIEW

**Comment by chip-miller** [comment]
I can confirm that this pull request fixes Issue #22 
```ruby
NoMethodError: undefined method `type_cast_from_database' for "":String
```

**Comment by AhmedNadar** [comment]
@chip-miller I have added to my model but still not working? How did you get it to work?

**Comment by chip-miller** [comment]
@AhmedNadar - I pointed my Gemfile to this fork (and didn't really need to make any other changes).
```ruby
  gem "activerecord-tableless", ">= 1.3.4",  git:'https://github.com/david135/activerecord-tableless.git'
```
I am not sure how you are using activerecord-tableless... In my situation I am using it to create a ``DummyClass`` to test an ActiveSupport::Concern. Using (Rails 4.2, Postgres)
```ruby
class UuidableDummy < ActiveRecord::Base
 has_no_table
 column :foo
 
 include Uuidable
 has_public_id :foo, prefix:'BAR'
end

describe Uuidable do
  subject { UuidableDummy.new }
  #etc.
end
```
I hope this is helpful.

**Comment by AhmedNadar** [comment]
@chip-miller Today I learned something new about target specific fork, thanks to you.
This solved my issue, it is really helpful. Here is my code:  
```ruby
class Ewoks < ActiveRecord::Base 
  has_no_table
  column :name, :string 
  column :email, :string 
  column :role, :string
  validates_presence_of :name, :email, :role 
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i 
  validates_length_of :role, :maximum => 100
end
```
Hope this fix would get merged.

**Comment by remofritzsche** [comment]
Are there any news on this fix? We'd be quite eager for a new release. Thanks a lot for your consideration.

**Comment by helloenvoy-andrew** [comment]
+1

**Comment by DerekH** [comment]
+1

**Comment by kreintjes** [comment]
+1
However, it does not work in combination with the pg gem when having column type :string. Using type :varchar can be used as workaround, but is not ideal.

**Comment by bekicot** [comment]
+1

**Comment by romenigld** [comment]
Thank's chip-miller I do:
` gem "activerecord-tableless", ">= 1.3.4",  git:'https://github.com/david135/activerecord-tableless.git'`
and works.

**Comment by liaden** [comment]
:+1:

**Comment by mayrsascha** [comment]
Thank's chip-miller I do:
gem "activerecord-tableless", ">= 1.3.4", git:'https://github.com/david135/activerecord-tableless.git'
and works for us too.

**Comment by fguillen** [comment]
+1

**Comment by dalupus** [comment]
+1

**Comment by TheBrockEllis** [comment]
I can confirm that this pr does indeed fix the issue with rails 4.2.x (I am using rails 4.2.5 as part of the learn-rails.com by Daniel Kehoe)

**Comment by amitfriedman12** [comment]
I am having the same issue as @kreintjes

```
class CampaignsWrapper < ActiveRecord::Base
  has_no_table

  column :remote_service_id, :string

end
```
wrapper = CampaignsWrapper.new(remote_service_id: "123456789")
Then in the command line:
```
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  type "string" does not exist
LINE 1: SELECT 'string'::regtype::oid
               ^
: SELECT 'string'::regtype::oid
from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
```
